apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::610054414151:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-GI2KJ7F6O064
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::610054414151:role/UdacityFlaskDeployCBKubectlRole
      username: build     
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
